# services:
#   web-scrcpy:
#     image: ghcr.io/neanc/web-scrcpy:latest
#     container_name: web-scrcpy
#     hostname: web-scrcpy
#     networks:
#       - web-scrcpy
#     ports:
#       - "5000:5000"
#     volumes:
#       # - /dev/bus/usb:/dev/bus/usb   # 挂载 USB 设备，若需要 USB 链接请取消注释
#       - ./data:/app/data
#     privileged: true
#     restart: unless-stopped
#     environment:
#       - FLASK_ENV=production
#       - FLASK_APP=app.py

#   web-scrcpy-custom:
#     container_name: web-scrcpy-custom
#     image: web-scrcpy:test
#     restart: unless-stopped
#     ports:
#       - "5001:5000"
#     stdin_open: true
#     tty: true
#     command: >
#       sh -c "
#       . /app/venv/bin/activate &&
#       adb connect 192.168.1.111:5555 &&
#       adb connect 192.168.1.127:5555 &&
#       python3 app.py --port 5000 --video_bit_rate 256000
#       "

# networks:
#    web-scrcpy:
#      name: web-scrcpy